export enum PaymentStatus {
  PENDING_PAYMENT = "PENDING_PAYMENT",
  PAID = "PAID",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  EXPIRED = "EXPIRED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  REFUNDED = "REFUNDED",
}
